name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2005530@ds.study.iitm.ac.in
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ allows push access

      - name: Commit step - parameswaran2k@gmail.com
        run: |
          echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Auto commit at $(date -u)" || echo "No changes to commit"
          git push
